name: rag
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - langchain==1.0.7
    - langchain-chroma==1.0.0
    - langchain-community==0.4.1
    - langchain-huggingface==1.0.1
    - langchain-ollama==1.0.0
    - model2vec==0.7.0
    - pip-chill==1.0.3
    - platformdirs==4.2.2
    - sentence-transformers==5.1.2
    - streamlit==1.51.0
    - ipykernel==7.1.0
    - pytrec-eval==0.5
